import type { Metadata } from 'next';
import './globals.css';
import { UserProgressProvider } from '@/hooks/useUserProgress';
import GlobalTopBar from '@/components/GlobalTopBar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <UserProgressProvider>
          <GlobalTopBar />
          {children}
        </UserProgressProvider>
      </body>
    </html>
  );
}
